/** Common country codes for phone input - code without +, e.g. "91" for India */
export const COUNTRY_CODES = [
  { code: '91', country: 'India', dial: '+91' },
  { code: '1', country: 'US/Canada', dial: '+1' },
  { code: '44', country: 'UK', dial: '+44' },
  { code: '971', country: 'UAE', dial: '+971' },
  { code: '966', country: 'Saudi Arabia', dial: '+966' },
  { code: '65', country: 'Singapore', dial: '+65' },
  { code: '60', country: 'Malaysia', dial: '+60' },
  { code: '61', country: 'Australia', dial: '+61' },
  { code: '81', country: 'Japan', dial: '+81' },
  { code: '86', country: 'China', dial: '+86' },
  { code: '33', country: 'France', dial: '+33' },
  { code: '49', country: 'Germany', dial: '+49' },
  { code: '39', country: 'Italy', dial: '+39' },
  { code: '34', country: 'Spain', dial: '+34' },
  { code: '31', country: 'Netherlands', dial: '+31' },
  { code: '27', country: 'South Africa', dial: '+27' },
  { code: '234', country: 'Nigeria', dial: '+234' },
  { code: '254', country: 'Kenya', dial: '+254' },
  { code: '92', country: 'Pakistan', dial: '+92' },
  { code: '880', country: 'Bangladesh', dial: '+880' },
  { code: '94', country: 'Sri Lanka', dial: '+94' },
  { code: '977', country: 'Nepal', dial: '+977' },
  { code: '62', country: 'Indonesia', dial: '+62' },
  { code: '63', country: 'Philippines', dial: '+63' },
  { code: '84', country: 'Vietnam', dial: '+84' },
  { code: '66', country: 'Thailand', dial: '+66' },
  { code: '90', country: 'Turkey', dial: '+90' },
  { code: '7', country: 'Russia', dial: '+7' },
  { code: '55', country: 'Brazil', dial: '+55' },
  { code: '52', country: 'Mexico', dial: '+52' },
  { code: '57', country: 'Colombia', dial: '+57' },
  { code: '54', country: 'Argentina', dial: '+54' },
  { code: '48', country: 'Poland', dial: '+48' },
  { code: '46', country: 'Sweden', dial: '+46' },
  { code: '47', country: 'Norway', dial: '+47' },
  { code: '45', country: 'Denmark', dial: '+45' },
  { code: '358', country: 'Finland', dial: '+358' },
  { code: '353', country: 'Ireland', dial: '+353' },
  { code: '64', country: 'New Zealand', dial: '+64' },
  { code: '82', country: 'South Korea', dial: '+82' },
  { code: '852', country: 'Hong Kong', dial: '+852' },
  { code: '853', country: 'Macau', dial: '+853' },
  { code: '886', country: 'Taiwan', dial: '+886' },
] as const;
